include:
  - ./docker-compose-base.yml
services:
  api:
    container_name: tnnai-api
    build: 
      context: .
      dockerfile: Dockerfile
    image: tnnai:latest
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
    # depends_on: [postgres, redis]
    ports: ["8000:8000"]
    command: >
      sh -c "UVICORN_NO_UVLOOP=1 UVICORN_NO_HTTP_TOOLS=1
             python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
    networks:
      - tnn_ai